-- MySQL Script generated by MySQL Workbench
-- Fri Jul  1 13:42:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog-voyage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog-voyage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog-voyage` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci ;
USE `blog-voyage` ;

-- -----------------------------------------------------
-- Table `blog-voyage`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-voyage`
.`Articles` (
  `idarticles` INT NOT NULL,
  `contain` LONGTEXT NULL,
  `date` DATETIME NULL,
  `picture` VARCHAR(450) NULL,
  PRIMARY KEY (`idarticles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-voyage`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-voyage`.`service` (
  `descriptifarticle` VARCHAR(45) NULL,
  `pictureservice` VARCHAR(450) NULL,
  `type` VARCHAR(45) NULL,
  `idservice` INT NOT NULL,
  PRIMARY KEY (`idservice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-voyage`.`villes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-voyage`.`villes` (
  `idvilles` INT NOT NULL,
  `idarticles` INT NOT NULL,
  `pictureville` VARCHAR(450) NULL,
  `idservice` INT NULL,
  PRIMARY KEY (`idvilles`),
  CONSTRAINT `idarticles`
    FOREIGN KEY (`idarticles`)
    REFERENCES `blog-voyage`.`Articles` (`idarticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idservice`
    FOREIGN KEY (`idservice`)
    REFERENCES `blog-voyage`.`service` (`idservice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idarticles_idx` ON `blog-voyage`.`villes` (`idarticles` ASC) VISIBLE;

CREATE INDEX `idservice_idx` ON `blog-voyage`.`villes` (`idservice` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `blog-voyage`.`pays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-voyage`.`pays` (
  `idpays` INT NOT NULL,
  `idarticles` INT NULL,
  `picturepays` VARCHAR(450) NULL,
  `idservice` INT NULL,
  `descriptifpays` LONGTEXT NULL,
  PRIMARY KEY (`idpays`),
  CONSTRAINT `idarticles`
    FOREIGN KEY (`idarticles`)
    REFERENCES `blog-voyage`.`Articles` (`idarticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idservice`
    FOREIGN KEY (`idservice`)
    REFERENCES `blog-voyage`.`service` (`idservice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idarticles_idx` ON `blog-voyage`.`pays` (`idarticles` ASC) VISIBLE;

CREATE INDEX `idservice_idx` ON `blog-voyage`.`pays` (`idservice` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `blog-voyage`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-voyage`.`user` (
  `iduser` INT NOT NULL,
  `adress@` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-voyage`.`panier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-voyage`.`panier` (
  `idpanier` INT NOT NULL,
  `iduser` INT NULL,
  `idservice` INT NULL,
  `prix` INT NULL,
  `quantité` INT NULL,
  `total` INT NULL,
  PRIMARY KEY (`idpanier`),
  CONSTRAINT `iduser`
    FOREIGN KEY ()
    REFERENCES `blog-voyage`.`user` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idservice`
    FOREIGN KEY ()
    REFERENCES `blog-voyage`.`service` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
